version: '3.8'
services:
  news-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.newsmcp
    ports:
      - "8012:8002"
    env_file:
      - .env
    environment:
      - NEWS_MCP_SERVER_PORT=8002
      - NEWS_MCP_SERVER_HOST=news-mcp-server
    volumes:
      - ./src/:/app/src/
    restart: on-failure
    networks:
      - agent-network

  stock-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.stockmcp
    ports:
      - "8011:8001"
    env_file:
      - .env
    environment:
      - STOCK_MCP_SERVER_PORT=8001
      - STOCK_MCP_SERVER_HOST=stock-mcp-server
    volumes:
      - ./src/:/app/src/
    restart: on-failure
    networks:
      - agent-network

  streamlit-server:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "5551:5521"
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STOCK_MCP_SERVER_HOST=stock-mcp-server
      - STOCK_MCP_SERVER_PORT=8001
      - NEWS_MCP_SERVER_HOST=news-mcp-server
      - NEWS_MCP_SERVER_PORT=8002
    volumes:
      - .:/app/
    depends_on:
      - stock-mcp-server
      - news-mcp-server
    networks:
      - agent-network
  gradio-server:
    build:
      context: .
      dockerfile: Dockerfile.gradio
    ports:
      - "7861:7860"
    env_file:
      - .env
    environment:
      - GRADIO_SERVER_PORT=7860
      - STOCK_MCP_SERVER_HOST=stock-mcp-server
      - STOCK_MCP_SERVER_PORT=8001
      - NEWS_MCP_SERVER_HOST=news-mcp-server
      - NEWS_MCP_SERVER_PORT=8002
    volumes:
      - .:/app/
    depends_on:
      - stock-mcp-server
      - news-mcp-server
    networks:
      - agent-network
networks:
  agent-network:
    driver: bridge